# March 28

## Merging all three human translated files

### To do/done

* merging three
* removing duplicates

In [1]:
import pandas as pd
import numpy as np

In [2]:
tri = pd.read_csv("trimaster.csv")
ar = pd.read_csv("armaster.csv")
cn = pd.read_csv("cnmaster.csv")

In [3]:
tri.shape

(557, 5)

In [4]:
ar.shape

(531, 3)

In [5]:
cn.shape

(542, 3)

In [6]:
ar.head()

  en     ar  pos
0  0    صفر  num
1  1   واحد  num
2  2  إثنان  num
3  3  ثلاثة  num
4  4  أربعة  num

In [7]:
cn.drop(0, inplace=True)

In [8]:
cn.shape

(541, 3)

In [9]:
arcn = pd.merge(ar, cn, on="en", how="outer")

In [10]:
arcn.drop(539, inplace=True)

In [11]:
for i, row in arcn.iterrows():
    col = list(arcn)
    if row.pos_x != row.pos_y:
        print(i)
        for c in col:
            print(arcn.loc[i, c])
        
        init = "pos_x"
        while True:
            print("col to change:")
            init = input()
            
            if init == "x":
                break
                
            if init == "drop":
                arcn.drop(i, inplace=True)
                break
            print("change to val:")
            row[init] == input()
        
        print()

67
After *.
 بعد *.
vp
*之后
adv
col to change:

KeyboardInterrupt:

In [ ]:
arcn.loc[320, 'pos_x'] = "sent"
arcn.loc[321, 'pos_x'] = "sent"
arcn.loc[363, 'pos_x'] = "np"
arcn.loc[376, 'pos_x'] = "vp"
arcn.loc[377, 'pos_y'] = "sent"
arcn.loc[379, 'pos_x'] = "sent"
arcn.loc[379, 'pos_x'] = "adv"
arcn.loc[380, 'en'] = "police"
arcn.loc[380, 'cn'] = "警察"
arcn.loc[380, 'ar'] = "الشرطة"
arcn.loc[388, 'pos_x'] = "vp"
arcn.loc[388, 'pos_x'] = "adv"
arcn.loc[404, 'pos_x'] = "np"
arcn.drop(452, inplace=True)
arcn.drop(540, inplace=True)

In [ ]:
arcn.to_csv("merged0328.csv")

In [ ]:
arcn.drop('pos_y', axis=1, inplace=True)

In [ ]:
arcn = arcn.rename(columns={'pos_x': 'pos'})

In [ ]:
tricopy = tri.copy()
#tricopy = tricopy.drop(['pos'], axis=1)

In [ ]:
merge2 = pd.merge(arcn, tricopy, on="en", how="outer")

In [ ]:
merge2.shape

In [ ]:
merge2.drop('Unnamed: 0', axis=1, inplace=True)
merge2.head()

In [ ]:
merge2 = merge2.fillna('')

In [ ]:
merge2.tail(10)

In [ ]:
todrop = [543, 544, 545,552,553,554]
for i in todrop:
    merge2.drop(todrop, inplace=True)

In [ ]:
for i, row in merge2.iterrows():
    if row.ar_x == "":
        merge2.loc[i, "ar_x"] = row.ar_y
        merge2.loc[i, "cn_x"] = row.cn_y
        merge2.loc[i, "pos_x"] = row.pos_y

In [ ]:
for i, row in merge2.iterrows():
    if row.ar_x == "":
        print(i)
        print(row.en)
        print()

In [ ]:
merge2.head(10)

In [ ]:
merge2.drop(['ar_y','cn_y','pos_y'],axis=1,inplace=True)

In [ ]:
final = merge2.rename(columns={'pos_x': 'pos',"ar_x":"ar","cn_x":"cn"})

In [ ]:
final.head()

In [ ]:
final.tail()

In [ ]:
final.to_csv("finalmaster.csv")

In [ ]:
final.loc[571,'ar']

# April 3rd

### To do

* add city and country names
* fix unit (dollars, RMB etc) spacing bug
* extend corpus: AR with open source dic and CN with HSK words
* remove cardinal numbers
* ar json parsing word order flipping

In [12]:
temp = pd.read_csv("finalmaster.csv")

In [13]:
city = pd.read_csv("countries_cities.csv")

In [16]:
temp = temp.drop("Unnamed: 0", axis=1)

In [17]:
temp.head()

  en     ar  pos cn
0  0    صفر  num  零
1  1   واحد  num  一
2  2  إثنان  num  二
3  3  ثلاثة  num  三
4  4  أربعة  num  四

In [18]:
city.head()

            en         ar     cn pos
0  Afghanistan  أفغانستان    阿富汗  np
1      Albania    ألبانيا  阿尔巴尼亚  np
2      Algeria    الجزائر  阿尔及利亚  np
3      Andorra     أندورا    安道尔  np
4       Angola     أنغولا    安哥拉  np

In [19]:
cat = pd.concat([temp, city], ignore_index=True)

In [23]:
cat.tail()

            ar    cn             en pos
930    ويندسور    温莎        Windsor  np
931    سراييفو  萨拉热窝       Sarajevo  np
932  هونغ كونغ    香港      Hong Kong  np
933      ماكاو    澳门          Macau  np
934    نيويورك   纽约市  New York City  np

In [32]:
cat[cat.duplicated(['cn'], keep="first")]

,ar,cn,en,pos
82,ملاءات السرير,床单,bedsheets,np
84,بيرة,啤酒,beer,np
271,انا مريض.,我生病了。,I'm sick.,sent
272,أنا آسف.,对不起。,I'm sorry.,sent
316,هل لي بالحصول على كأس من *؟,可以来一杯*吗？,May I have a glass of *?,vp
338,ليلة/ليل,晚上好。,night,np
360,"برتقالي (the color or the adjective), برتقال (...",橙色,orange,np
369,قلم حبر,笔,pen,np
381,لحم خنزير,猪肉,pork,np
384,بطاقة بريدية,明信片,postcard,np
390,موس حلاقة,剃刀,razor,np
437,هاتف,电话,telephone,np
448,هما,他们,they (two people),np
461,فرشاة أسنان,牙刷,toothbrush,np
462,فرشاة أسنان,牙刷,toothbrush,np
463,فرشاة أسنان,牙刷,toothbrush,np
473,مظلة,雨伞,umbrella,np
474,مظلة,雨伞,umbrella,np
475,مظلة,雨伞,umbrella,np
490,ما اسمك؟,你叫什么名字？,What is your name?,sent
491,ما اسمك؟,你叫什么名字？,What is your name?,sent
492,ما اسمك؟,你叫什么名字？,What is your name?,sent
543,بخير، شكرا لك.,"很好, 谢谢。","I'm fine, thank you.",sent
548,أنا لا أفهم,我听不懂。,I don't understand.,sent

In [35]:
cat.drop([462, 463, 474, 475, 491, 492, 493], inplace=True)

ValueError: labels [462 463 474 475 492 493] not contained in axis

In [46]:
cat[cat.duplicated(['en'], keep="last")]

,ar,cn,en,pos
359,"برتقالي (the color or the adjective), برتقال (...",橙色,orange,np
368,قلم حبر,笔,pen,np
380,لحم خنزير,猪肉,pork,np
383,بطاقة بريدية,明信片,postcard,np
389,موس حلاقة,剃刀,razor,np
436,هاتف,电话,telephone,np
460,فرشاة أسنان,牙刷,toothbrush,np
472,مظلة,雨伞,umbrella,np
489,ما اسمك؟,你叫什么名字？,What is your name?,sent

In [47]:
cat.drop([359, 368, 380, 383, 389, 436, 460, 472, 489], inplace=True)

In [51]:
cat[cat.duplicated(['ar'], keep="first")]

                    ar       cn                       en   pos
201                ذهب       金色                     gold   adj
263  أريد ايجار سيارة.     我想租车  I'd like to rent a car.  sent
387               ادفع        推                     push   adv
425               شارع        街                   street    np
519        أين الحمام؟   厕所在哪里？     Where is the toilet?  sent
543     بخير، شكرا لك.  很好, 谢谢。     I'm fine, thank you.  sent
548        أنا لا أفهم    我听不懂。      I don't understand.  sent
557               نعم.      是的。                    Yeah.    vp
639            اليونان      匈牙利                  Hungary    np

In [50]:
cat[cat.duplicated(['ar'], keep="last")]

                    ar       cn                                     en   pos
187     بخير، شكرا لك.  很好, 谢谢。                       Fine, thank you.  sent
199                ذهب        去                                     go    vp
242        أنا لا أفهم    我听不懂。  I don't understand (something heard).  sent
259  أريد ايجار سيارة.   我想要租车。                  I want to rent a car.  sent
367               ادفع        付                                    pay    vp
396               شارع        路                                   road    np
517        أين الحمام؟  洗手间在哪里？                 Where is the bathroom?  sent
535               نعم.        是                                   Yes.  sent
631            اليونان       希腊                                 Greece    np

In [52]:
cat.loc[639, 'ar'] = "المجر"

In [54]:
cat[cat.duplicated(['cn'], keep="first")]

                              ar        cn                        en   pos
82                 ملاءات السرير        床单                 bedsheets    np
84                          بيرة        啤酒                      beer    np
271                    انا مريض.     我生病了。                 I'm sick.  sent
272                     أنا آسف.      对不起。                I'm sorry.  sent
316  هل لي بالحصول على كأس من *؟  可以来一杯*吗？  May I have a glass of *?    vp
338                     ليلة/ليل      晚上好。                     night    np
448                          هما        他们         they (two people)    np
543               بخير، شكرا لك.   很好, 谢谢。      I'm fine, thank you.  sent
548                  أنا لا أفهم     我听不懂。       I don't understand.  sent

In [53]:
cat[cat.duplicated(['cn'], keep="last")]

,ar,cn,en,pos
60,البيرة,啤酒,a beer,np
81,ملاءة سرير,床单,bedsheet,np
178,لو سمحت,对不起。,Excuse me. (coming through),sent
187,بخير، شكرا لك.,"很好, 谢谢。","Fine, thank you.",sent
202,مساء الخير.,晚上好。,Good evening.,sent
236,انا مريض,我生病了。,I am sick.,sent
242,أنا لا أفهم,我听不懂。,I don't understand (something heard).,sent
315,هل لي بالحصول على كوب من *؟,可以来一杯*吗？,May I have a cup of *?,vp
447,هم,他们,they (m/mixed),np

In [55]:
cat.drop(60, inplace=True)
cat.drop(81, inplace=True)
cat.loc[338, 'cn'] = "晚上"
cat.loc[338, 'ar'] = "ليلة"

In [73]:
tofix = pd.DataFrame()

for i, row in cat.iterrows():
    if "/" in str(row.en) or "/" in str(row.cn) or "/" in str(row.ar):
        tofix = tofix.append(row)

In [74]:
tofix

,ar,cn,en,pos
138,كانون الأول‎/ ديسمبر,十二月,December,np
140,إسهال,泻肚子/拉肚子,diarrhoea,np
297,كانون الثاني‎/ يناير,一月,January,np
299,تموز/‎ يوليو,七月,July,np
300,حزيران/‎ يونيو,六月,June,np
312,آذار‎ / مارس,三月,March,np
313,أيار‎/ مايو,五月,May,np
327,المزيد/أكثر,更,more,adj
334,رقبة,颈项/脖子,neck,np
347,تشرين الثاني/‎ نوفمبر,十一月,November,np
350,تشرن الأول‎ /أكتوبر,十月,October,np
364,عذراً/معذرة؟,可以再重复一遍吗？,Pardon me?,sent
366,بعد ال*. / بعد أن تتخطى ال*.,传*,Past the *.,vp
374,أرجوك، تعال/تعالي معي.,请跟我过来,Please come with me.,sent
402,سجق/نقاق,香肠,sausage,np
406,أيلول‎/ سبتمبر,九月,September,np
422,توقف! لص/سارق‏! ‎,住手！小偷！,Stop! Thief!,sent
433,تاكسي‏/سيارة أجرة,出租车,taxi,np
434,سائق سيارة أجرة/تاكسي,出租车司机,Taxi driver,np
447,هم,他们,they (m/mixed),np
454,خبز التوست/المحمص,吐司,toast,np
494,ما هو توقيت الفطور/العشاء؟,早/晚餐是什么时候？,What time is breakfast/supper?,sent

In [77]:
cat.loc[138,'ar']="ديسمبر"
cat.loc[297, 'ar'] ="يناير"
cat.loc[299, 'ar'] ="يوليو"
cat.loc[300, 'ar'] ="يونيو"
cat.loc[312, 'ar'] ="مارس"
cat.loc[313, 'ar'] ="مايو"
cat.loc[327, 'ar'] ="أكثر"
cat.loc[334, 'cn'] ="脖子"
cat.loc[347, 'ar'] ="نوفمبر"
cat.loc[350, 'ar'] ="أكتوبر"
cat.loc[402, 'ar'] ="سجق"
cat.loc[406, 'ar'] ="سبتمبر"
cat.loc[433, 'ar'] ="تاكسي"
cat.loc[434, 'ar'] ="سائق تاكسي"
cat.loc[447, 'en'] ="they"
cat.loc[454, 'ar'] ="خبز محمص"
cat.loc[494, 'ar'] ="ما هو توقيت *؟"
cat.loc[494, 'en'] ="What time is *?"
cat.loc[494, 'cn'] ="*是什么时候？"

In [78]:
cat.shape

(917, 4)

In [79]:
cat.to_csv("master0403.csv")

In [84]:
cat.head(52)

                  ar     cn                 en  pos
0                صفر      零                  0  num
1               واحد      一                  1  num
2              إثنان      二                  2  num
3              ثلاثة      三                  3  num
4              أربعة      四                  4  num
5               خمسة      五                  5  num
6                ستة      六                  6  num
7               سبعة      七                  7  num
8             ثمانية      八                  8  num
9               تسعة      九                  9  num
10              عشرة      十                 10  num
11          إحدى عشر     十一                 11  num
12          إثنا عشر     十二                 12  num
13         ثلاثة عشر     十三                 13  num
14         أربعة عشر     十四                 14  num
15          خمسة عشر     十五                 15  num
16           ستة عشر     十六                 16  num
17          سبعة عشر     十七                 17  num
18        ثمانية عشر     十八                 18  num
19          تسعة عشر     十九                 19  num
20             عشرون     二十                 20  num
21       واحد وعشرون    二十一                 21  num
22      إثنان وعشرون    二十二                 22  num
23      ثلاثة وعشرون    二十三                 23  num
24            ثلاثون     三十                 30  num
25            أربعون     四十                 40  num
26             خمسون     五十                 50  num
27              ستون     六十                 60  num
28             سبعون     七十                 70  num
29            ثمانون     八十                 80  num
30             تسعون     九十                 90  num
31              مائة     一百                100  num
32       مائة و واحد   一百零一                101  num
33        مائة وعشرة   一百一十                110  num
34    مائة و أحد عشر  一百一十一                111  num
35             مئتين     二百                200  num
36         ثلاث مائة     三百                300  num
37          خمس مائة     五百                500  num
38               ألف     一千               1000  num
39             ألفين     二千               2000  num
40         عشرة آلاف     一万             10,000  num
41  عشرة آلاف و واحد   一万零一             10,001  num
42  عشرة آلاف وإثنان   一万零二             10,002  num
43         عشرون الف     二万             20,000  num
44         خمسون ألف     五万             50,000  num
45          مائة ألف     十万            100,000  num
46          مئتي ألف    二十万            200,000  num
47             مليون    一百万          1,000,000  num
48       عشرة ملايين    一千万         10,000,000  num
49        مائة مليون     一亿        100,000,000  num
50            مليار‎     十亿      1,000,000,000  num
51           تريليون     一兆  1,000,000,000,000  num

In [86]:
for i, row in cat.iterrows():
    if i == 52:
        break
    print(row.en)
    inp = str(input())
    if inp == "drop":
        cat.drop(i, inplace=True)
    else:
        cat.loc[i, 'en'] = inp

0
zero
1
one
2
two
3
three
4
four
5
five
6
six
7
seven
8
eight
9
nine
10
ten
11
drop
12
drop
13
drop
14
drop
15
drop
16
drop
17
drop
18
drop
19
drop
20
drop
21
drop
22
drop
23
drop
30
drop
40
drop
50
drop
60
drop
70
drop
80
drop
90
drop
100
hundred
101
drop
110
drop
111
drop
200
two hundred
300
drop
500
five hundred
1000
thousand
2000
two thousand
10,000
ten thousand
10,001
drop
10,002
drop
20,000
twenty thousand
50,000
fifty thousand
100,000
hundred thousand
200,000
drop
1,000,000
million
10,000,000
ten million
100,000,000
hundred million
1,000,000,000
billion
1,000,000,000,000
trillion

In [87]:
cat.head(50)

                      ar       cn                    en   pos
0                    صفر        零                  zero   num
1                   واحد        一                   one   num
2                  إثنان        二                   two   num
3                  ثلاثة        三                 three   num
4                  أربعة        四                  four   num
5                   خمسة        五                  five   num
6                    ستة        六                   six   num
7                   سبعة        七                 seven   num
8                 ثمانية        八                 eight   num
9                   تسعة        九                  nine   num
10                  عشرة        十                   ten   num
31                  مائة       一百               hundred   num
35                 مئتين       二百           two hundred   num
37              خمس مائة       五百          five hundred   num
38                   ألف       一千              thousand   num
39                 ألفين       二千          two thousand   num
40             عشرة آلاف       一万          ten thousand   num
43             عشرون الف       二万       twenty thousand   num
44             خمسون ألف       五万        fifty thousand   num
45              مائة ألف       十万      hundred thousand   num
47                 مليون      一百万               million   num
48           عشرة ملايين      一千万           ten million   num
49            مائة مليون       一亿       hundred million   num
50                مليار‎       十亿               billion   num
51               تريليون       一兆              trillion   num
52  من فضلك أعطني * و *.  请给我*和*。     * and * , please.    vp
53               ‏* أيام       *天              * day(s)   prt
54              ‏* ساعات     *个小时             * hour(s)   prt
55             * لا يعمل       坏了     * is not working.    vp
56              ‏* دقائق      *分钟           * minute(s)   prt
57               *  أشهر      *个月            * month(s)   prt
58              ‏* أسبوع     *个星期             * week(s)   prt
59              ‏* سنوات       *年             * year(s)   prt
61                قارورة       一瓶              a bottle    np
62         كأس من النبيذ      一杯酒       a glass of wine    np
63               نصف لتر      一品脱                a pint    np
64         طاولة ل * شخص    *人的座位  a table for * people    np
65                   بطن       腹部               abdomen    np
66                   بعد       之后                 after   adv
67             بعد الظهر       下午             afternoon    np
68             مكيف هواء       空调        airconditioner    np
69                 طائرة       飞机              airplane    np
70                  مطار       机场               airport    np
71         هل أنا معتقل؟   我被捕了吗？    Am I under arrest?  sent
72         نيسان‎\ أبريل       四月                 April    np
73           قريب من هنا       转角    Around the corner.  sent
74            آب‎\ أغسطس       八月                August    np
75                  سبيل       大道                avenue    np
76                   ظهر        背                  back    np
77                  مشرب       酒吧                  bars    np

In [89]:
cat.shape

(890, 4)

In [93]:
cat = cat.reset_index()
cat.drop('index', axis=1, inplace=True)

In [95]:
cat.drop('level_0', axis=1, inplace=True)
cat.head(50)

                      ar       cn                    en   pos
0                    صفر        零                  zero   num
1                   واحد        一                   one   num
2                  إثنان        二                   two   num
3                  ثلاثة        三                 three   num
4                  أربعة        四                  four   num
5                   خمسة        五                  five   num
6                    ستة        六                   six   num
7                   سبعة        七                 seven   num
8                 ثمانية        八                 eight   num
9                   تسعة        九                  nine   num
10                  عشرة        十                   ten   num
11                  مائة       一百               hundred   num
12                 مئتين       二百           two hundred   num
13              خمس مائة       五百          five hundred   num
14                   ألف       一千              thousand   num
15                 ألفين       二千          two thousand   num
16             عشرة آلاف       一万          ten thousand   num
17             عشرون الف       二万       twenty thousand   num
18             خمسون ألف       五万        fifty thousand   num
19              مائة ألف       十万      hundred thousand   num
20                 مليون      一百万               million   num
21           عشرة ملايين      一千万           ten million   num
22            مائة مليون       一亿       hundred million   num
23                مليار‎       十亿               billion   num
24               تريليون       一兆              trillion   num
25  من فضلك أعطني * و *.  请给我*和*。     * and * , please.    vp
26               ‏* أيام       *天              * day(s)   prt
27              ‏* ساعات     *个小时             * hour(s)   prt
28             * لا يعمل       坏了     * is not working.    vp
29              ‏* دقائق      *分钟           * minute(s)   prt
30               *  أشهر      *个月            * month(s)   prt
31              ‏* أسبوع     *个星期             * week(s)   prt
32              ‏* سنوات       *年             * year(s)   prt
33                قارورة       一瓶              a bottle    np
34         كأس من النبيذ      一杯酒       a glass of wine    np
35               نصف لتر      一品脱                a pint    np
36         طاولة ل * شخص    *人的座位  a table for * people    np
37                   بطن       腹部               abdomen    np
38                   بعد       之后                 after   adv
39             بعد الظهر       下午             afternoon    np
40             مكيف هواء       空调        airconditioner    np
41                 طائرة       飞机              airplane    np
42                  مطار       机场               airport    np
43         هل أنا معتقل؟   我被捕了吗？    Am I under arrest?  sent
44         نيسان‎\ أبريل       四月                 April    np
45           قريب من هنا       转角    Around the corner.  sent
46            آب‎\ أغسطس       八月                August    np
47                  سبيل       大道                avenue    np
48                   ظهر        背                  back    np
49                  مشرب       酒吧                  bars    np

In [96]:
cat.to_csv("master0403.csv")

In [105]:
cat.loc[44,'ar'] = "أبريل"
cat.loc[46,'ar'] = "أغسطس"

In [108]:
cat.head(100)

,ar,cn,en,pos
0,صفر,零,zero,num
1,واحد,一,one,num
2,إثنان,二,two,num
3,ثلاثة,三,three,num
4,أربعة,四,four,num
5,خمسة,五,five,num
6,ستة,六,six,num
7,سبعة,七,seven,num
8,ثمانية,八,eight,num
9,تسعة,九,nine,num
10,عشرة,十,ten,num
11,مائة,一百,hundred,num
12,مئتين,二百,two hundred,num
13,خمس مائة,五百,five hundred,num
14,ألف,一千,thousand,num
15,ألفين,二千,two thousand,num
16,عشرة آلاف,一万,ten thousand,num
17,عشرون الف,二万,twenty thousand,num
18,خمسون ألف,五万,fifty thousand,num
19,مائة ألف,十万,hundred thousand,num
20,مليون,一百万,million,num
21,عشرة ملايين,一千万,ten million,num
22,مائة مليون,一亿,hundred million,num
23,مليار‎,十亿,billion,num
24,تريليون,一兆,trillion,num
25,من فضلك أعطني * و *.,请给我*和*。,"* and * , please.",vp
26,‏* أيام,*天,* day(s),prt
27,‏* ساعات,*个小时,* hour(s),prt
28,* لا يعمل,坏了,* is not working.,vp
29,‏* دقائق,*分钟,* minute(s),prt
...,...,...,...,...
70,مؤخرة,屁股,buttocks,np
71,مقهى,咖啡室,cafe,np
72,هل استطيع الحصول على حقيبة؟,我可以要一个袋子吗？,Can I get a bag?,sent
73,هل أستطيع الحصول على تأمين؟,我可以买保险吗？,Can I get insurance?,sent
74,هل استطيع دفع غرامة أدفع غرامة الآن؟,我可以缴交罚款吗？,Can I just pay a fine now?,sent
75,قائمة الطعام، من فضلك؟,请给我看看菜单.,"Can I look at the menu, please?",sent
76,هل يمكنني الحصول على مكالمة هاتفية؟,我可以打个电话吗？,Can I make a telephone call?,sent
77,هل يمكنني حجز موعد؟,我可以预约吗？,Can I make an appointment?,sent
78,هل استطيع القيام بمكالمة دولية من هنا؟,可以打国际电话吗?,Can I make international calls here?,sent
79,هل يمكنني الطبع من هنا؟,我可以复印吗？,Can I print here?,sent
80,أيمكنني إستخدام هاتفك؟,我可以用您的手机吗？,Can I use your cell phone?,sent
81,أيمكنني استخدام هاتفك النقال؟,我可以用您的电话吗？,Can I use your phone?,sent
82,هل يمكنك تحويل مال لي؟,你可以帮我换钱吗？,Can you change money for me?,sent
83,هل يمكنك أن تحضر طبيب؟,你可以帮我找一位医生吗？,Can you get a doctor?,sent
84,هل يمكنك أن تريني أين هو على الخريطة؟,你可以在地图上指给我看?,Can you show me on the map?,sent
85,عل يمكنك تحدث ال*؟,你可以说*吗？,Can you speak *?,vp
86,هل يمكنك اقتراح فندق آخر؟,你有其他推荐的酒店吗？,Can you suggest another hotel?,sent
87,اين *؟,你可以告诉我*在那里吗？,Can you tell me where * is?,vp
88,هل تستطيع إيقاظي الساعة *؟,请在明天早上*点钟叫醒我。,Can you wake me at *?,vp
89,هل يمكنك أن تكتب لي الإسم و العنوان؟,你可以写下名字和地址吗？,Can you write the name and address down?,sent
90,سيارة,汽车,car,np
91,مياه غازية,碳酸水,carbonated water,np
92,أوراق مالية,现金,cash,np
93,رخيص,便宜,cheap,adj
94,أرخص,比较便宜,cheaper,adj
95,شيك,支票,check,np
96,جبنة,奶酪,cheese,np
97,صدر,胸部,chest,np
98,دجاج‎\ فراخ,鸡,chicken,np
99,أنظف,清洁工,cleaner,np

In [110]:
cat.loc[98,'ar'] = "دجاج"

In [116]:
for i, row in cat.iterrows():
    if "\\" in row.ar:
        print(i)
        print(row)

In [115]:
cat.loc[155, "ar"] = "فبراير"

In [117]:
cat.to_csv("master0403.csv")

In [152]:
l1 = pd.read_csv("hskl1.txt",delimiter="\t",header=None)
l2 = pd.read_csv("hskl2.txt",delimiter="\t",header=None)
l3 = pd.read_csv("hskl3.txt",delimiter="\t",header=None)
hsk = pd.DataFrame()

In [153]:
hsk = pd.concat([l1, l2])
hsk = pd.concat([hsk, l3])

In [154]:
hsk.head()

   0  1     2    3                                               4
0  的  的   de5   de  indicates possession, like adding 's to a noun
1  我  我   wo3   wǒ                                           I; me
2  你  你   ni3   nǐ                                  you (singular)
3  是  是  shi4  shì                                 be; is; are; am
4  了  了   le5   le        indicates a completed or finished action

In [155]:
hsk = hsk.drop([1,2,3], axis=1)

In [156]:
hsk = hsk.rename(columns={0:"cn",4:"en"})

In [158]:
hsk

      cn                                                 en
0      的     indicates possession, like adding 's to a noun
1      我                                              I; me
2      你                                     you (singular)
3      是                                    be; is; are; am
4      了           indicates a completed or finished action
5      不                                            no; not
6      在        at; on; in; indicates an action in progress
7      他                                            he; him
8     我们                                             we; us
9      好                                               good
10     有                                               have
11     这                                               this
12     会                                        know how to
13     吗  indicates a yes/no question (added to a statem...
14    什么  what? (replaces the noun to turn a statement i...
15     说                                              speak
16     她                                                she
17     想             think; believe; suppose; would like to
18     一                                       one; once; a
19     很                                        very; quite
20     人                                person; man; people
21     那                                         that; then
22     来                     come; arrive; ever since; next
23     都                                          all; both
24     个                               general measure word
25     能                                       can; be able
26     去                                       go; to leave
27     和                                          and; with
28     做                                           do; make
29     上                                          above; up
..   ...                                                ...
270   北方            north; the northern part of the country
271   上网                      to surf the web; to go online
272   季节                               season; time; period
273    渴                                            thirsty
274   发烧                                       have a fever
275   不但                                           not only
276   空调                                   air conditioning
277  照相机                                             camera
278    春                            spring (season); joyful
279    伞                                  umbrella; parasol
280   公斤                                           kilogram
281   个子                             height; stature; build
282   熊猫                                              panda
283   刷牙                                  brush one's teeth
284   复习                                  revise; to review
285    冬                                             winter
286   请假                                to ask for time off
287   中文                                 Chinese (language)
288    秋                         autumn; fall; harvest time
289   句子                                           sentence
290  行李箱                                    trunk; suitcase
291   筷子                                         chopsticks
292   皮鞋                                      leather shoes
293   爬山                                  mountain climbing
294   黑板                                         blackboard
295  感兴趣                                   be interested in
296   词典                                         dictionary
297   留学                                       study abroad
298   刮风                              windy; to blow (wind)
299   黄河                                       Yellow River

[601 rows x 2 columns]